/**
 * AI Tag Scrubbing & Pre-Render Metadata Test Suite
 * Batch Music Visualizer Engine
 */

import path from 'path';
import fs from 'fs-extra';
import { readID3Tags, scrubAITags, writeID3Tags } from '../metadata/id3-engine.js';

async function runAiTagScrubbingTests() {
  console.log('================================================================');
  console.log('🧹 RUNNING AI METADATA SCRUBBING & COPYRIGHT UTILITY TEST SUITE');
  console.log('================================================================\n');

  const testDir = path.resolve('./test_output_ai_scrubbing');
  await fs.ensureDir(testDir);

  const sampleAudioPath = path.join(testDir, 'sample_suno_track.mp3');

  // Copy sample audio file for testing
  const demoAudio = path.resolve('./demo_album_input/01 - Midnight Piano Trap.mp3');
  if (fs.existsSync(demoAudio)) {
    await fs.copy(demoAudio, sampleAudioPath);
  } else {
    // Fallback mock audio file if demo not present
    await fs.writeFile(sampleAudioPath, Buffer.alloc(1024));
  }

  console.log('--- TEST GROUP 1: Embed Suno AI Watermark Metadata Tags ---');
  await writeID3Tags(sampleAudioPath, {
    title: 'Midnight Suno Beat',
    artist: 'Made with Suno AI',
    album: 'Suno AI Generated Album',
    publisher: 'Suno AI Publisher',
    comment: 'Generated by Suno.ai v3'
  });

  const dirtyTags = await readID3Tags(sampleAudioPath);
  console.log(`  dirtyTags.artist: "${dirtyTags.artist}"`);
  console.log(`  dirtyTags.comment: "${dirtyTags.comment}"`);
  if (dirtyTags.artist?.includes('Suno')) {
    console.log('  ✅ [PASS] Suno AI tags successfully embedded for test baseline');
  }

  console.log('\n--- TEST GROUP 2: Execute scrubAITags() ---');
  const cleanedTags = await scrubAITags(sampleAudioPath, {
    artist: 'Antigravity Records',
    publisher: 'Antigravity Audio Studio',
    comment: '© 2026 Antigravity Records. All Rights Reserved.'
  });

  console.log(`  cleanedTags.artist: "${cleanedTags.artist}"`);
  console.log(`  cleanedTags.publisher: "${cleanedTags.publisher}"`);
  console.log(`  cleanedTags.comment: "${cleanedTags.comment}"`);

  if (!cleanedTags.artist?.includes('Suno') && cleanedTags.artist === 'Antigravity Records') {
    console.log('  ✅ [PASS] AI generation watermarks successfully scrubbed!');
  } else {
    console.error('  ❌ [FAIL] Suno watermark still present!');
    process.exit(1);
  }

  if (cleanedTags.comment?.includes('© 2026 Antigravity Records')) {
    console.log('  ✅ [PASS] Custom copyright notice embedded successfully!');
  }

  console.log('\n================================================================');
  console.log('🎉 ALL AI TAG SCRUBBING & COPYRIGHT TESTS PASSED SUCCESSFULLY!');
  console.log('================================================================\n');
}

runAiTagScrubbingTests().catch(err => {
  console.error('Test Suite Failed:', err);
  process.exit(1);
});
